### ISSUE TITLE
GPU version

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/pixel_level_land_classification#11]
Are you considering a GPU version of the classification routine? Right now you have to wait several seconds for the classification of the unseen regions.

**Comment by mawah** [comment]
Hi @lmiroslaw,

If your GPU is not already in use by another program, CNTK should automatically use the device both during training and inference. If ArcGIS Pro, the training script, or another notebook that imports CNTK are running when you start the inference notebook, then these scripts may have locked the GPU, forcing the inference notebook to default to execution on CPU. An extra CNTK command can help check which device is being used:

```
>>> cntk.device.use_default_device()
Selected CPU as the process wide default device.
```

If you find that the inference notebook cannot make use of the GPU, we recommend closing ArcGIS Pro and any open notebooks (using the "Close and Halt" option, so that no kernels which imported CNTK are left running).

Another reason that inference may be slower than expected is that the neural network's output size is 128 pixels x 128 pixels, so we have used a tiling strategy to perform predictions on large regions. It's possible to achieve speedups by changing the I/O dimensions of the network (which doesn't require retraining since the network is fully convolutional) or by implementing minibatching to perform inference on multiple "tiles" at once. Currently we don't have plans to include sample code for those techniques in this repository, however.

**Comment by mawah** [comment]
Closing this issue as it appears to have been due to the GPU being locked by a separate process, and no reply has been received for a few weeks.
