### ISSUE TITLE
Permission Denied on AZCopy

### ISSUE THREAD

**Issue by f-tonini** [Azure/pixel_level_land_classification#14]
Hello,

I am running the AzCopy cell on my GEODSVM (see screenshot) but am getting a "permission denied" error on the command line (see screeshot) that prevents the download of the sample data and training images to complete this training.

Any advice on possible solutions and cause of error?
![2](https://user-images.githubusercontent.com/1470540/55574025-5fffc380-56d9-11e9-8601-ea43830f3c0e.png)
![1](https://user-images.githubusercontent.com/1470540/55574038-668e3b00-56d9-11e9-8f75-be0c1e2697f0.png)

**Comment by yangsiyu007** [comment]
Hi @f-tonini, sorry about that - we recently moved the resources and neglected to update the links and SAS keys. Please substitute with the following:
Source: https://ai4ehackathons.blob.core.windows.net/landcovertutorial
SourceSAS: ?se=2020-04-06T06%3A59%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=YD6mbqnmYTW%2Bs6guVndjQSQ8NUcV8F9HY%2BhPNWiulIo%3D

We will amend the files shortly.

**Comment by f-tonini** [comment]
Hi @yangsiyu007,

I replaced the lines of code you suggested, but still receive a permission denied message (see screenshots below). What could be the issue here?

![GEODSVM Error_1](https://user-images.githubusercontent.com/1470540/55633512-892c5c80-578a-11e9-81bb-cc35f22f9a33.png)
![GEODSVM Error_2](https://user-images.githubusercontent.com/1470540/55633516-8af62000-578a-11e9-960f-f7707c4f0293.png)

**Comment by f-tonini** [comment]
@yangsiyu007  when you click on the Source https://ai4ehackathons.blob.core.windows.net/landcovertutorial you provided, it also says 'Resource not Found". Could you possibly double check? It's been running for 20 minutes and nothing gets downloaded from the AzCopy command above.

**Comment by yangsiyu007** [comment]
Hi @f-tonini, It looks to me that the "permission denied" error is related to Jupyter Notebook unable to execute the command line command (the ! at the beginning of this cell tells Jupyter Notebook to execute it as a command line command instead of as a line of Python script). Are you doing this on the GeoAI DSVM?

As a workaround, you can issue the command on the command line yourself (instead of asking Jupyter Notebook to do it). Open a Command Prompt and give the command
```
AzCopy /Source:https://ai4ehackathons.blob.core.windows.net/landcovertutorial /SourceSAS:"?se=2020-04-06T06%3A59%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=YD6mbqnmYTW%2Bs6guVndjQSQ8NUcV8F9HY%2BhPNWiulIo%3D" /Dest:D:\pixellevellandclassification1 /S
```
and there should be some printout saying x out of 34 files have been transferred. I'm assuming you're using the GeoAI DSVM, in which case AzCopy is installed already. I just tested this and this SAS key should be valid.

**Comment by f-tonini** [comment]
@yangsiyu007 it works now when running the command in the standalone CMD prompt. It just does not seem to work when run within the Jupyter Notebook cell block. I will close the issue for now as resolved as the data was downloaded successfully! Thanks for helping!

**Comment by zglezgle** [comment]
It looks like the token has expired. Would you please help me with it? Thanks!

failed to perform copy command due to error: cannot start job due to error: cannot list blobs. Failed with error -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.7.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d494cb38-a01e-00c0-3254-55a2b9000000
Time:2020-07-08T18:22:44.5733951Z, Details:
   AuthenticationErrorDetail: Signed expiry time [Mon, 06 Apr 2020 06:59:00 GMT] must be after signed start time [Wed, 08 Jul 2020 18:22:44 GMT]
   Code: AuthenticationFailed
   GET https://ai4ehackathons.blob.core.windows.net/landcovertutorial?comp=list&include=metadata&restype=container&se=2020-04-06t06%3A59%3A00z&sig=-REDACTED-&sp=rl&sr=c&sv=2018-03-28&timeout=901
   User-Agent: [AzCopy/10.4.3 Azure-Storage/0.7 (go1.13; Windows_NT)]
   X-Ms-Client-Request-Id: [cd745c08-3f32-4c3a-4ce1-a3a8c1ae5897]
   X-Ms-Version: [2019-02-02]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [489]
   Content-Type: [application/xml]
   Date: [Wed, 08 Jul 2020 18:22:43 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [d494cb38-a01e-00c0-3254-55a2b9000000]
